print("tipos de datos primitivos")
print("Tipo de dato cadena de caracteres")
print("string. (str)")
print("TIPO DE DATO ENTERO(INT)")
print(34)
print(6)
print(1)
print("TIPO DE DATO FLOTANTE(FLOAT)")
print(2.17)
